# HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://hugo.io/hugo-modules/
##
 
imports:
  - path: github.com/HugoBlox/kit/modules/integrations/netlify
  - path: github.com/HugoBlox/kit/modules/blox
  - path: github.com/HugoBlox/kit/modules/slides
 
# Install any Hugo Blox within the `hugo-blox/blob` folder
mounts:
  - source: hugo-blox/blob/community
    target: layouts/_partials/blob/community/
    files:
      - '**html'
  - source: hugo-blox/blob/all-access
    target: layouts/_partials/blob/
    files:
      - '**html'
  - source: hugo-blox/blob
    target: assets/dist/community/blob/
    files:
      - '**css'
  - source: layouts
    target: layouts
  - source: assets
    target: assets
 
page:
  - path: "{,**}/**"
    params:
      author: admin
